# Generated by Django 4.2.6 on 2023-10-13 03:59

from django.db import migrations, models
import pendencias.models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencia',
            name='codigo_pa',
            field=models.CharField(help_text='Código único do processo', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='cpf',
            field=models.CharField(help_text='CPF da pessoa', max_length=11, validators=[pendencias.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada da pendência'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='nome_pessoa',
            field=models.CharField(help_text='Nome da pessoa relacionada à pendência', max_length=100),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='status',
            field=models.BooleanField(default=False, help_text='Status da pendência (resolvida ou não)'),
        ),
    ]
