# Generated by Django 4.2.6 on 2023-10-13 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0002_alter_pendencia_codigo_pa_alter_pendencia_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencia',
            name='data_de_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
