# Generated by Django 4.2.6 on 2023-10-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0003_pendencia_data_de_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_execucao', models.DateTimeField(auto_created=True)),
                ('nome_user', models.CharField(max_length=100)),
                ('nome_pendencia', models.CharField(max_length=100)),
                ('acao', models.CharField(choices=[('I', 'Inseriu Pendência'), ('S', 'Troca de Status'), ('E', 'Excluiu a Pendência')], max_length=1)),
            ],
        ),
    ]
