# Generated by Django 4.2.6 on 2023-10-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0004_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='cpf',
            field=models.CharField(default=11111111111, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_de_execucao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
