# Generated by Django 4.2.6 on 2023-10-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0005_historico_cpf_alter_historico_data_de_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencia',
            name='codigo_pa',
            field=models.CharField(help_text='Código Renach', max_length=10),
        ),
    ]
